CREATE TABLE EMP( EMPNO NUMBER(4,0), ENAME VARCHAR2(10),
JOB
VARCHAR2(9), MGR NUMBER(4,0), HIREDATE DATE, SAL
NUMBER(7,2), COMM
NUMBER(7,2), DEPTNO NUMBER(2,0), CONSTRAINT PK_EMP
PRIMARY KEY
(EMPNO), CONSTRAINT FK_DEPTNO FOREIGN KEY (DEPTNO)
REFERENCES DEPT (DEPTNO) );
INSERT INTO EMP VALUES( 7839, 'KING', 'PRESIDENT', NULL,
TO_DATE('17-11-
1981','DD-MM-YYYY'), 5000, NULL, 10 );
INSERT INTO EMP VALUES( 7698, 'BLAKE', 'MANAGER', 7839,
TO_DATE('1-5-
1981','DD-MM-YYYY'), 2850, NULL, 30 );
INSERT INTO EMP VALUES( 7782, 'CLARK', 'MANAGER', 7839,
TO_DATE('9-6-
1981','DD-MM-YYYY'), 2450, NULL, 10 );
INSERT INTO EMP VALUES( 7566, 'JONES', 'MANAGER', 7839,
TO_DATE('2-4-
1981','DD-MM-YYYY'), 2975, NULL, 20 );
SELECT * FROM EMP;
CREATE TABLE DEPT( DEPTNO NUMBER(2,0), DNAME VARCHAR2(14),
LOC
VARCHAR2(13), CONSTRAINT PK_DEPT PRIMARY KEY (DEPTNO) ); 
INSERT INTO DEPT (DEPTNO, DNAME, LOC) VALUES(10,
'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT VALUES(20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPT VALUES(30, 'SALES', 'CHICAGO');
INSERT INTO DEPT VALUES(40, 'OPERATIONS', 'BOSTON');
SELECT * FROM DEPT;
SELECT ENAME, DNAME, JOB, EMPNO, HIREDATE, LOC FROM EMP,
DEPT WHERE
EMP.DEPTNO = DEPT.DEPTNO ORDER BY ENAME;
SELECT DNAME, COUNT(*) COUNT_OF_EMPLOYEES FROM DEPT,
EMP WHERE
DEPT.DEPTNO = EMP.DEPTNO GROUP BY DNAME ORDER BY 2 DESC;
SELECT DEPTNO, MAX(SAL),MIN(SAL), FROM EMP GROUP BY
DEPTNO;
SELECT SAL, DEPTNO FROM EMP ORDER BY SAL DESC;
SELECT DEPTNO FROM EMP GROUP BY DEPTNO;
ALTER TABLE EMP ADD EMAIL VARCHAR(30);
TRUNCATE TABLE DEPT;
DROP TABLE DEPT;
