CREATE TABLE STDMARKS (ROLL_NO INT(), STUDENT_NAME VARCHAR2(10), SUBJECT
VARCHAR2(10), MARKS INT);
INSERT INTO STDMARKS VALUES(1,'RAVI','C++',75);
INSERT INTO STDMARKS VALUES(1,'RAVI','ORACLE',84);
INSERT INTO STDMARKS VALUES(1,'RAVI','JAVA',95);
INSERT INTO STDMARKS VALUES(1,'RAVI','OS',62);
INSERT INTO STDMARKS VALUES(2,'VIVEK','C++',46);
INSERT INTO STDMARKS VALUES(2,'VIVEK','ORACLE',70);
INSERT INTO STDMARKS VALUES(2,'VIVEK','JAVA',55);
INSERT INTO STDMARKS VALUES(2,'VIVEK','OS',56);
INSERT INTO STDMARKS VALUES(3,'RAJ','C++',82);
INSERT INTO STDMARKS VALUES(3,'RAJ','ORACLE',84);
INSERT INTO STDMARKS VALUES(3,'RAJ','JAVA',74);
INSERT INTO STDMARKS VALUES(3,'RAJ','OS',92);
INSERT INTO STDMARKS VALUES(4,'MAHESH','C++',43);
INSERT INTO STDMARKS VALUES(4,'MAHESH','ORACLE',49);
INSERT INTO STDMARKS VALUES(4,'MAHESH','JAVA',68);
INSERT INTO STDMARKS VALUES(4,'MAHESH','OS',35);
SELECT * FROM STDMARKS;
SELECT SUBJECT, AVG(MARKS) AS "AVERAGE MARKS" FROM STDMARKS GROUP BY
SUBJECT;
SELECT ROLL_NO, AVG(MARKS) AS "AVERAGE MARKS" FROM STDMARKS GROUP BY
ROLL_NO;
UPDATE STDMARKS SET STUDENT_NAME = 'ALFRED SCHMIDT' WHERE ROLL_NO = 1;
DELETE FROM STDMARKS WHERE ROLL_NO = 1;
SELECT SUBJECT, MIN(MARKS) AS "MIN MARKS" FROM STDMARK GROUP BY SUBJECT;
SELECT * FROM STDMARK WHERE MARKS<50;
SELECT * FROM STDMARK WHERE MARKS>80; 
