CREATE TABLE HOSPITAL ( HOSP_NAME VARCHAR(40) PRIMARY
KEY, COUNTRY
VARCHAR(30),ADDRESS VARCHAR(50));
CREATE TABLE MEDICINE ( REG_NO NUMBER PRIMARY KEY,
MED_NAME VARCHAR(20) NOT NULL, PRICE NUMBER(4, 3),
EXP_DATE DATE);
CREATE TABLE PATIENT ( ID NUMBER PRIMARY KEY, NAME
VARCHAR(30), AGE
INTEGER, GENDER CHAR(1));
INSERT INTO HOSPITAL VALUES
((‘King Hamad University Hospital’, ‘Kingdom of Bahrain’, ‘Bahrain’),
(‘Mayo Clinic’, ‘United States’, ‘4500 San Pablo Road, US’),
(‘Bahrain Defence Force Hospital’, ‘Kingdom of Bahrain’, ‘Bahrain’),
(‘Salamaniya Hospital’, ‘Kindgom of Bahrain’, ‘Manama, Bahrain’),
(‘St Thomas' Hospital London’, ‘United Kingdom’, ‘London’));
SELECT * FROM HOSPITAL;
INSERT INTO MEDICINE VALUES
((020, ‘Adol Syrup’, 0.300, '15/MAY/2023'),
(021, ‘Amoxil Capsules’, 0.700, '10/MAR/2023'),
(022, ‘Aspirin’, 1.000, '09/DEC/2023'),
(023, ‘Bonjela Gel’, 0.400, '23/SEP/2024'),
(024, ‘Paracetamol’, 1.200, '17/MAY/2024'));
Select * from MEDICINE;
INSERT INTO PATIENT VALUES
((100000001, ‘Sara’,27, 'F'),
(100000002, ‘Ahmed’, 59, 'M'),
(100000003, ‘Abdulla’,45, 'M'),
(100000004, ‘Mariam’, 40, 'F'),
(100000005, ‘Fatema’, 64, 'F'));
Select * from PATIENT;
Create VIEW PATIENT_DATA AS SELECT HOS_NAME, NAME,
MED_NAME FROM
HOSPITAL,MEDICINE, PATIENT;
SELECT * FROM PATIENT_DATA;
CREATE VIEW MED_DATA AS SELECT NAME, MED_NAME, AGE
FROM MEDICINE, PATIENT;
SELECT * FROM MED_DATA;
CREATE VIEW HOS_DATA AS SELECT NAME, HOS_NAME, AGE
FROM HOSPITAL, PATIENT;
SELECT * FROM HOS_DATA;
